Add 3 files HTML, CSS and JS
DavidSE12/FlappyBird pull request #1
Opened 2024-09-30 00:14 UTC by DavidSE12

2024-10-01 03:13 UTC, huythangphan requested changes
em update thêm 1 vài thứ nữa nhe:
1. PR title có nghĩa hơn ví dụ `Add ...` hoặc `Update ...` hoặc `Fix bug ...`
2. bổ sung thêm PR description theo IPO
3. deploy lên github pages và gán link vào PR description để a test thử

2024-10-01 03:13 UTC, huythangphan commented on index.css
> +    height: 800px;
CS1: em sử dụng rem thay cho px mục đích là để sau này có tăng base font size thì các elements đều được scale theo

2024-10-01 03:13 UTC, huythangphan commented on index.css
> +
CS1: em remove unnecessary empty lines

2024-10-01 03:13 UTC, huythangphan commented on main.js
> +let block = document.getElementById("block");
CS1: a thấy variable này ko được sử dụng thì ko cần phải khai báo

2024-10-01 03:13 UTC, huythangphan commented on main.js
> +let bird = document.getElementById("bird");
CS1: a thấy 2 variables này ko thay đổi nên dùng let chưa hợp lý lắm

2024-10-01 03:13 UTC, huythangphan commented on main.js
> +let jumping = 0;  // Flag to determine if the bird is jumping
CS5.1: em đặt tên biến phản ánh đúng data nó hold nhe

2024-10-01 03:13 UTC, huythangphan commented on main.js
> +    let holeleft =
CS5.1: em đặt tên biến phản ánh đúng data nó hold nhe

2024-10-02 22:55 UTC, DavidSE12 commented on index.css
> +    height: 800px;
Resolved

2024-10-02 22:55 UTC, DavidSE12 commented on index.css
> +
Resolved

2024-10-02 22:55 UTC, DavidSE12 commented on main.js
> +let block = document.getElementById("block");
Resolved

2024-10-02 22:55 UTC, DavidSE12 commented on main.js
> +let bird = document.getElementById("bird");
Resolved

2024-10-02 23:14 UTC, DavidSE12 commented on main.js
> +let jumping = 0;  // Flag to determine if the bird is jumping
Resolved

2024-10-02 23:14 UTC, DavidSE12 commented on main.js
> +    let holeleft =
Resolved

2024-10-04 03:06 UTC, huythangphan requested changes
PR title a thấy nen để là `Add flappy bird game` sau đó trong description đã có mô tả kỹ hơn là add những gì để đạt được `add flappy bird game` thì hợp lý hơn. em đang để là add files... thì a thấy nó hơi chung chung ko diễn tả được PR này thêm feature gì vào

2024-10-04 03:06 UTC, huythangphan commented on Images/check
CS1: a thấy file này empty và ko được sử dụng do đó em nên remove nhe

2024-10-04 03:06 UTC, huythangphan commented on main.js
> +    // Process: Check for game over conditions
CS1: logic này em nên tách ra 1 function riêng check game over sau này em muốn sửa logic lúc nào game over chỉ cần vào function đó thay vì tìm ở trong đoạn code dài như này

2024-10-04 03:06 UTC, huythangphan commented on main.js
> +    // Process: Generate a random position for the hole's top between 200px and 450px
CS1: những thông tin như min/max hole top position, starting position of bird, game over threshold là constant do đó em nên define constant variables ở trên cùng sau này mình muốn sửa logic adjust các thông tin này thì chỉ cần sửa ở constant sẽ dễ hơn

2024-10-04 03:06 UTC, huythangphan commented on main.js
> +        alert("game over score " + (score - 1) )
CS1: em nên sử dụng template string để improve readability. sau này có chèn nhiều variable vào cũng sẽ dễ đọc hơn

2024-10-06 14:53 UTC, huythangphan approved these changes

2024-10-06 23:30 UTC, merged